### ISSUE TITLE
此BLOG系统有一点问题，D70G3申请二改

### ISSUE THREAD

**Issue by thepiationesl** [wusheng233github/wusheng233-blog-system#1]
此BLOG系统有一点问题，D70G3申请二改。测试站点：http://imnt.evai.pl/wsbk

**Comment by wusheng233github** [comment]
在v0.4.1修复了

**Comment by thepiationesl** [comment]
这个我可以fork到我的仓库进行二改开源吗？比方说我想写个安装程序，还有加注释

**Comment by thepiationesl** [comment]
一堆BUG。。。真的，我得加注释了

**Comment by wusheng233github** [comment]
你可以修改本仓库了

**Comment by wusheng233github** [comment]
高端的后端往往不用注释

**Comment by thepiationesl** [comment]
我想我该自己创建一个仓库了，你这仓库我push半天都push不了

**Comment by wusheng233github** [comment]
你从Releases下载个v0.5放到你的仓库就行啊

**Comment by thepiationesl** [comment]
我放源代码，我不喜欢ZIP式打包，那样BSD解压起来特别费劲，我现在就把你邀请进去

**Comment by wusheng233github** [comment]
ok

**Comment by thepiationesl** [comment]
我想单独开一个仓库整一个MySQL版本，我不喜欢txt式存储，然后我想再加个自己需要的功能，请问同意二改吗
